package org.deeplearning4j.scalphagozero.board

import org.deeplearning4j.scalphagozero.strip
import org.scalatest.FunSpec

class GoBoardSerializerTest extends FunSpec {

  describe("Serialize a board") {
    var board = GoBoard(9)
    it("It should have this format") {
      board = board.placeStone(BlackPlayer, Point(2, 2))
      board = board.placeStone(WhitePlayer, Point(3, 3))
      board = board.placeStone(BlackPlayer, Point(2, 3))
      board = board.placeStone(WhitePlayer, Point(5, 4))

      assertResult(strip("""------------
                     | 9 .........
                     | 8 .XX......
                     | 7 ..O......
                     | 6 .........
                     | 5 ...O.....
                     | 4 .........
                     | 3 .........
                     | 2 .........
                     | 1 .........
                     |   ABCDEFGHI
                     |------------""")) { board.toString }
    }
  }

  describe("Serialize another board") {
    var board = GoBoard(9)
    it("It should have this format") {
      board = board.placeStone(BlackPlayer, Point(1, 1))
      board = board.placeStone(WhitePlayer, Point(3, 3))
      board = board.placeStone(BlackPlayer, Point(2, 3))
      board = board.placeStone(WhitePlayer, Point(5, 4))

      assertResult(strip("""------------
                           | 9 X........
                           | 8 ..X......
                           | 7 ..O......
                           | 6 .........
                           | 5 ...O.....
                           | 4 .........
                           | 3 .........
                           | 2 .........
                           | 1 .........
                           |   ABCDEFGHI
                           |------------""")) { board.toString }
    }

  }
}
