package org.deeplearning4j.scalphagozero.board

import org.deeplearning4j.scalphagozero.strip
import org.scalatest.FunSpec

class GoBoardSerializerTest extends FunSpec {

  describe("Serialize a board") {
    val board = GoBoard(9)
    it("It should have this format") {
      board.placeStone(BlackPlayer, Point(2, 2))
      board.placeStone(WhitePlayer, Point(3, 3))
      board.placeStone(BlackPlayer, Point(2, 3))
      board.placeStone(WhitePlayer, Point(5, 4))

      assertResult(strip("""-----------
                     |  123456789
                     |1 .........
                     |2 .XX......
                     |3 ..O......
                     |4 .........
                     |5 ...O.....
                     |6 .........
                     |7 .........
                     |8 .........
                     |9 .........
                     |-----------""")) { board.toString }
    }
  }

  describe("Serialize another board") {
    val board = GoBoard(9)
    it("It should have this format") {
      board.placeStone(BlackPlayer, Point(1, 1))
      board.placeStone(WhitePlayer, Point(3, 3))
      board.placeStone(BlackPlayer, Point(2, 3))
      board.placeStone(WhitePlayer, Point(5, 4))

      assertResult(strip("""-----------
                           |  123456789
                           |1 X........
                           |2 ..X......
                           |3 ..O......
                           |4 .........
                           |5 ...O.....
                           |6 .........
                           |7 .........
                           |8 .........
                           |9 .........
                           |-----------""")) { board.toString }
    }

  }
}
